src/ManagerTaskService/Controllers/ManagerTaskController.cs
namespace ManagerTaskService.Controllers
{
    using ManagerTask.Data;
    using System;
    using System.Linq;
    using System.Web.Mvc;

    /// <summary>
    /// The manager task controller
    /// </summary>
    [Authorize]
    public class ManagerTaskController : Controller
    {
        private IManagerTaskDataAccess managerTaskDataAccess;

        /// <summary>
        /// Initializes a new instance of the <see cref="ManagerTaskController"/> class
        /// </summary>
        /// <param name="_managerTaskDataAccess">The manager task data access interface</param>
        public ManagerTaskController(IManagerTaskDataAccess _managerTaskDataAccess)
        {
            managerTaskDataAccess = _managerTaskDataAccess;
        }

        /// <summary>
        /// The index
        /// </summary>
        /// <returns>The index view result</returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Adds the driver.
        /// </summary>
        /// <returns>The add driver action view result</returns>
        [HttpGet]
        public ActionResult AddDriver()
        {
            return this.View();
        }

        /// <summary>
        /// Adds the driver
        /// </summary>
        /// <param name="driver">The driver.</param>
        /// <param name="dateJoinedCompany">The date the dirver joined the company.</param>
        /// <returns>The redirect result</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddDriver(string driver, DateTime? dateJoinedCompany)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var user = HttpContext.User;
                    if (user == null)
                    {
                        ViewBag.Error = "There is no manager found";
                        return View();
                    }

                    managerTaskDataAccess.AddDriver(driver, user.Identity.Name, dateJoinedCompany);
                    return RedirectToAction("GetDrivers");
                }
                catch (Exception e)
                {
                    ViewBag.Error = e.Message;
                }
            }

            return View();
        }

        /// <summary>
        /// Gets the driver
        /// </summary>
        /// <param name="name">The driver name.</param>
        /// <returns>The get dirver view result</returns>
        [HttpGet]
        public ActionResult GetDriver(string name)
        {
            try
            {
                var driver = managerTaskDataAccess.GetDriver(name);
                return View(driver);
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                return View();
            }
        }

        /// <summary>
        /// Gets the drivers
        /// </summary>
        /// <returns>The get drivers view result</returns>
        [HttpGet]
        public ActionResult GetDrivers()
        {
            try
            {
                var userName = HttpContext.User.Identity.Name;
                var drivers = managerTaskDataAccess.GetDrivers(userName).ToList();
                return View(drivers);
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                return View();
            }
        }

        /// <summary>
        /// Adds the check
        /// </summary>
        /// <returns>The add check view result</returns>
        [HttpGet]
        public ActionResult AddCheck()
        {
            return View();
        }


        /// <summary>
        /// Adds the check
        /// </summary>
        /// <param name="driver">The driver.</param>
        /// <param name="type">The check type.</param>
        /// <param name="success">The success flag.</param>
        /// <param name="date">The check time.</param>
        /// <returns>The add check view result</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCheck(string driver, CheckType type, bool success, DateTime date)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    managerTaskDataAccess.AddCheck(driver, type, success, date);
                    return RedirectToAction("GetChecksByDriver", new { driver });
                }
                catch (Exception e)
                {
                    ViewBag.Error = e.Message;
                }
            }

            return View();
        }

        /// <summary>
        /// Gets the checks by manager
        /// </summary>
        /// <returns>The check collection view result</returns>
        [HttpGet]
        public ActionResult GetChecksByManager()
        {
            try
            {
                var userName = HttpContext.User.Identity.Name;
                var checks = managerTaskDataAccess.GetChecksByManager(userName).ToList();
                return View(checks);
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                return View();
            }
        }

        /// <summary>
        /// Gets the checks by driver
        /// </summary>
        /// <param name="driver">The driver.</param>
        /// <returns>The check collection view result</returns>
        [HttpGet]
        public ActionResult GetChecksByDriver(string driver)
        {
            try
            {
                var checks = managerTaskDataAccess.GetChecksByDriver(driver).ToList();
                return View(checks);
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                return View();
            }
        }
    }
}

src/ManagerTaskService/Views/ManagerTask/AddCheck.cshtml
@model ManagerTask.Data.Driver
@{
    ViewBag.Title = "Add Check";
}
@if (ViewBag.Error != null)
{
    <p class="text-danger">@ViewBag.Error</p>
}

@if (ViewBag.Success != null)
{
    <p class="text-info">@ViewBag.Success</p>
}

@using (Html.BeginForm("AddCheck", "ManagerTask", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        <label class="col-md-2 control-label">Driver</label>
        <div class="col-md-3">
            <input class="form-control" data-val="true" data-val-required="The Name field is required." id="driver" name="driver" type="text" value="" required>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">Check Type</label>
        <div class="col-md-3">
            <select class="form-control" data-val="true" id="type" name="type">
                <option value="1">License</option>
                <option value="2">PhotocardExpired</option>
                <option value="3">ValidId</option>
                <option value="4">TrainingCompleted</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">Success</label>
        <div class="col-md-3">
            <select class="form-control" data-val="true" id="success" name="success">
                <option value="true">True</option>
                <option value="false">False</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">Date</label>
        <div class="col-md-3">
            <div class='input-group date ' id='datepicker'>
                <input type='text' class="form-control" data-val="true" data-val-required="The Name field is required." id="date" name="date" required />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-primary"><strong class="glyphicon-plus"></strong> Add</button>
        </div>
    </div>
}

<script type="text/javascript">
    var date = new Date().toDateString();
    $(function () {
        $('#datepicker').datetimepicker({
            defaultDate: date,
            format: 'YYYY/MM/DD HH:mm:ss'
        });
    });
</script>

src/ManagerTaskService/Views/ManagerTask/AddDriver.cshtml
@model ManagerTask.Data.Driver
@{
    ViewBag.Title = "Add Driver";
}

@if (ViewBag.Error != null)
{
    <p class="text-danger">@ViewBag.Error</p>
}

@if (ViewBag.Success != null)
{
    <p class="text-info">@ViewBag.Success</p>
}
@using (Html.BeginForm("AddDriver", "ManagerTask", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        <label class="col-md-2 control-label">Driver Name</label>
        <div class="col-md-3">
            <input class="form-control" data-val="true" data-val-required="The Name field is required." id="driver" name="driver" type="text" value="" required>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">Date Joined Company</label>
        <div class="col-md-3">
            <div class='input-group date' id='datepicker'>
                <input type='text' class="form-control time-input" data-val="true" data-val-required="The Name field is required." id="dateJoinedCompany" name="dateJoinedCompany" required/>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-primary"><strong class="glyphicon-plus"></strong> Add</button>
        </div>
    </div>
}
<script type="text/javascript">
    var date = new Date().toDateString();
    $(function () {
        $('#datepicker').datetimepicker({
            defaultDate: date,
            format: 'YYYY/MM/DD HH:mm:ss'
        });
    });
</script>

src/ManagerTaskService/Views/ManagerTask/GetChecksByDriver.cshtml
@using ManagerTask.Data

@model List<Check>
@{
    ViewBag.Title = "Checks";
}

@if (ViewBag.Error != null)
{
    <p class="text-danger warning">@ViewBag.Error</p>
}
@if (Model != null && Model.Count > 0)
{
    <div class="row">
        <table id="checks" class="table table-responsive table-hover">
            <thead>
                <tr>
                    <th>Driver</th>
                    <th>Success</th>
                    <th>Check Type</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var check in Model)
                {
                    <tr>
                        <td>@check.Driver.Name</td>
                        <td>@check.Success</td>
                        <td>@((CheckType)check.Type)</td>
                        <td>@check.Date</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <p class="text-danger warning">There is no check found for him</p>
}
<script>
    var filtersConfig = {
        base_path: '/Scripts/tablefilter/',
        col_1: 'select',
        col_2: 'select',
        alternate_rows: true,
        rows_counter: true,
        btn_reset: true,
        loader: true,
        mark_active_columns: true,
        highlight_keywords: true,
        no_results_message: true,
        custom_options: {
            cols: [4],
            sorts: [true]
        },
        col_types: [
            'string', 'string', 'string', 'date'
        ],
        extensions: [{
            name: 'sort'
        }],
        auto_filter: {
            delay: 0
        },
    };

    var tf = new TableFilter('checks', filtersConfig);
    tf.init();
</script>

src/ManagerTaskService/Views/ManagerTask/GetChecksByManager.cshtml
@using ManagerTask.Data
@model List<Check>
@{
    ViewBag.Title = "Checks";
}

@if (ViewBag.Error != null)
{
    <p class="text-danger warning">@ViewBag.Error</p>
}
@if (Model != null && Model.Count > 0)
{
    <div class="row">
        <table id="checks" class="table table-responsive table-hover">
            <thead>
                <tr>
                    <th>Driver</th>
                    <th>Success</th>
                    <th>Check Type</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var check in Model)
                {
                    <tr>
                        <td>@check.Driver.Name</td>
                        <td>@check.Success</td>
                        <td>@((CheckType)check.Type)</td>
                        <td>@check.Date</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <p class="text-danger warning">There is no check found</p>
}
<script>
    var filtersConfig = {
        base_path: '/Scripts/tablefilter/',
        col_1: 'select',
        col_2: 'select',
        alternate_rows: true,
        rows_counter: true,
        btn_reset: true,
        loader: true,
        mark_active_columns: true,
        highlight_keywords: true,
        no_results_message: true,
        custom_options: {
            cols: [4],
            sorts: [true]
        },
        col_types: [
            'string', 'string', 'string', 'date'
        ],
        paging: {
            results_per_page: ['Records: ', [6, 9]]
        },
        extensions: [{
            name: 'sort'
        }],
        auto_filter: {
            delay: 0
        },
    };

    var tf = new TableFilter('checks', filtersConfig);
    tf.init();
</script>

src/ManagerTaskService/Views/ManagerTask/GetDriver.cshtml
@model ManagerTask.Data.Driver
@{
    ViewBag.Title = "Driver";
}

<div>
    <label>Driver Name</label> @Model.Name
</div>
<div>
    <label>Manager Name</label> @Model.Manager.UserName
</div>

src/ManagerTaskService/Views/ManagerTask/GetDrivers.cshtml
@using ManagerTask.Data
@model List<Driver>
@{
    ViewBag.Title = "Drivers";
}

@if (ViewBag.Error != null)
{
    <p class="text-danger warning">@ViewBag.Error</p>
}
@if (Model != null && Model.Count > 0)
{
    <div class="row">
        <table id="drivers" class="table table-responsive table-hover">
            <thead>
                <tr>
                    <th>Driver</th>
                    <th>Manager</th>
                    <th>Date Joined Company</th>
                    <th>Checks</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var driver in Model)
                {
                    <tr>
                        <td>@driver.Name</td>
                        <td>@driver.Manager.UserName</td>
                        <td>@driver.DateJoinedCompany</td>
                        <td>@Html.ActionLink("Checks", "GetChecksByDriver", "ManagerTask", new { driver = driver.Name }, null)</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <p class="text-danger warning">There are no drivers found</p>
}
<script>
    var filtersConfig = {
        base_path: '/Scripts/tablefilter/',
        col_1: 'select',
        alternate_rows: true,
        rows_counter: true,
        btn_reset: true,
        loader: true,
        mark_active_columns: true,
        highlight_keywords: true,
        no_results_message: true,
        custom_options: {
            cols: [4],
            sorts: [true]
        },
        col_types: [
            'string', 'string', 'date', 'string'
        ],
        paging: true,
        extensions: [{
            name: 'sort'
        }],
        auto_filter: {
            delay: 0
        },
    };

    var tf = new TableFilter('drivers', filtersConfig);
    tf.init();
</script>

src/ManagerTaskService/Views/ManagerTask/Index.cshtml
@model ManagerTask.Data.Driver

@{
    ViewBag.Title = "Index";
}

@if (ViewBag.Error != null)
{
    <p class="text-danger">@ViewBag.Error</p>
}
else
{
    if (Model != null)
    {
        <div>
            <label>Name</label> @Model.Name
        </div>
        <div>
            <label>Email</label> @Model.Manager.UserName
        </div>
    }
    else
    {
        <p class="text-danger">No driver found</p>
    }
}